package com.example.prashantminiproject.model;

import lombok.Data;
import jakarta.persistence.*;

@Data
@Entity
public class Device {

    @Id
    private String kickstonId;

    private String deviceUsername;
    private String devicePassword;
    private String manufactureDateTime;
    private String manufactureFactoryPlace;

    // Constructors are generated by Lombok
}
