package com.example.prashantminiproject.model;

import lombok.Data;
import jakarta.persistence.*;

//import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

@Data
@Entity
public class House {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "house_id")
    private Long houseId;

    private String address;
    private String houseName;

    @ManyToOne
    private User admin;

    @OneToMany(mappedBy = "house", cascade = CascadeType.ALL)
    private List<Room> rooms;

    @ManyToMany
    @JoinTable(
            name = "user_house",
            joinColumns = @JoinColumn(name = "house_id"),
            inverseJoinColumns = @JoinColumn(name = "user_id"))
    private List<User> users;

    // Constructors are generated by Lombok

    public void addUser(User users) {
        if (this.users == null) {
            this.users = new ArrayList<>();
        }
        this.users.add(users);
    }
}
