package com.example.prashantminiproject.model;

import lombok.Data;

//import javax.persistence.*;
import jakarta.persistence.*;

@Data
@Entity
public class Room {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "room_id")
    private Long roomId;

    private String roomName;

    @ManyToOne
    private House house;

    // Constructors are generated by Lombok
}
