// Generated by https://quicktype.io

export interface APIQuote {
    _id:          string;
    content:      string;
    author:       string;
    tags:         string[];
    authorSlug:   string;
    length:       number;
    dateAdded:    string;
    dateModified: string;
}

// shift + ctrl + p -> ts -> name